apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    {{- if .Values.main.deploymentLabels }}
    {{- toYaml .Values.main.deploymentLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.main.deploymentAnnotations }}
  annotations:
    {{- toYaml .Values.main.deploymentAnnotations | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.main.autoscaling.enabled }}
  replicas: {{ .Values.main.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.main.deploymentStrategy.type }}
    {{- if eq .Values.main.deploymentStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ default "25%" .Values.main.deploymentStrategy.maxSurge  }}
      maxUnavailable: {{ default "25%" .Values.main.deploymentStrategy.maxUnavailable }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/type: master
  template:
    metadata:
      annotations:
        checksum/config: {{ print .Values.main | sha256sum }}
        {{- with .Values.main.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "n8n.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/type: master
        {{- with .Values.main.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "n8n.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.main.podSecurityContext | nindent 8 }}

      {{- with .Values.main.initContainers }}
      initContainers:
        {{ tpl (toYaml .) . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.main.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.main.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          {{- if or .Values.main.config .Values.main.secret }}
          envFrom:
            {{- if .Values.main.config }}
            - configMapRef:
                name: {{ include "n8n.fullname" . }}-app-config
            {{- end }}
            {{- if .Values.main.secret }}
            - secretRef:
                name: {{ include "n8n.fullname" . }}-app-secret
            {{- end }}
          {{- end }}

          {{- with .Values.main.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.main.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          ports:
            - name: http
              containerPort: {{ get (default (dict) .Values.main.config) "port" | default 5678 }}
              protocol: TCP

          {{- with .Values.main.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.main.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          resources:
            {{- toYaml .Values.main.resources | nindent 12 }}

          volumeMounts:
            - name: data
              mountPath: /home/node/.n8n
          {{- with .Values.main.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.main.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.main.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.main.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: data
          {{- include "n8n.pvc" . | nindent 10 }}
        {{- with .Values.main.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
