main:
  autoscaling:
    enabled: false
  replicaCount: 1

  # env — строго список
  extraEnv:
    - name: N8N_SECURE_COOKIE
      value: "false"
    - name: N8N_HOST
      value: "n8n.apps.infra-dev.p2.slotnet.tech"
    - name: N8N_PROTOCOL
      value: "https"

  # сервис и PVC — именно под main.*
  service:
    enabled: true
    type: ClusterIP
    port: 5678
    targetPort: 5678

  persistence:
    enabled: true
    size: 5Gi
    accessModes:
      - ReadWriteOnce
    storageClass: ceph-block
    storageClassName: ceph-block

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  pathType: Prefix
  hosts:
    - host: n8n.apps.infra-dev.p2.slotnet.tech
      paths:
        - /
