main:
  autoscaling:
    enabled: false
  replicaCount: 1

persistence:
  enabled: true
  size: 5Gi
  accessModes:
    - ReadWriteOnce
  # чарт, судя по шаблону, читает storageClassName; дефолт "standard"
  storageClassName: ceph-block

service:
  enabled: true
  type: ClusterIP
  port: 5678
  targetPort: 5678

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: n8n.apps.infra-dev.p2.slotnet.tech
      # важный момент: чарт ждёт СПИСОК СТРОК, не объектов
      paths:
        - /
