main:
  autoscaling:
    enabled: false
  replicaCount: 1

  # ⬇️ Сервис – под main.service.*
  service:
    enabled: true
    type: ClusterIP
    port: 5678
    targetPort: 5678

  # ⬇️ PVC – под main.persistence.*
  persistence:
    enabled: true
    size: 5Gi
    accessModes:
      - ReadWriteOnce
    # чарт часто использует storageClass, но на всякий кладём оба поля
    storageClass: ceph-block
    storageClassName: ceph-block

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: n8n.apps.infra-dev.p2.slotnet.tech
      paths:
        - path: /
          pathType: Prefix
