replicaCount: 1

image:
  repository: n8nio/n8n
  pullPolicy: IfNotPresent
  tag: ""

main:
  basicAuth:
    enabled: true
    user: admin
    password: securepass

  extraEnv:
    N8N_SECURE_COOKIE: "false"

  database:
    type: sqlite

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: standard

  service:
    port: 5678

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

  deploymentStrategy:
    type: "Recreate"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: n8n.localhost
      paths:
        - path: "/"
          pathType: Prefix
  tls: []

valkey:
  enabled: false

worker:
  enabled: false
  extraEnv: {}
  persistence:
    enabled: false
    type: emptyDir
    accessModes:
      - ReadWriteOnce
    size: 1Gi

webhook:
  enabled: false
  extraEnv: {}
  persistence:
    enabled: false
    type: emptyDir
    accessModes:
      - ReadWriteOnce
    size: 1Gi
